name: Build Reusable Workflow

on:
  workflow_call:
    inputs:
      language:
        description: 'Programming language for the build'
        required: true
        type: string
      environment:
        description: 'Deployment environment'
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      SNYK_TOKEN:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Set up Java (Zulu JDK)
      - name: Set up Java (version 11, Zulu)
        uses: actions/setup-java@v3
        with:
          java-version: '11'   # Configura a versão do Java 11
          distribution: 'zulu' # Usando Zulu JDK

      # Mudar para o diretório correto e executar o Maven
      - name: Install dependencies and build
        run: |
          cd java/java-pipelines
          mvn clean install

      - name: Run unit tests
        run: |
          cd java/java-pipelines
          mvn test

      # SonarQube scan step
      - name: Run SonarQube scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=jpvieirah_java-pipelines
            -Dsonar.organization=jpvieirah
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=java/java-pipelines/src
            -Dsonar.java.binaries=java/java-pipelines/target/classes
                  
      - name: Wait for SonarCloud Quality Gate
        uses: sonarsource/sonarcloud-quality-gate-action@v2.0.0
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: java-build
          path: java/java-pipelines/target/*.jar
