name: CI Java

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - "java/**"  # Dispara o workflow apenas se houver alterações na pasta "java"
  pull_request:
    branches: [ "develop", "main" ]
    paths:
      - "java/**"  # Dispara o workflow apenas se houver alterações na pasta "java"
  workflow_dispatch:

jobs:
  ci-java:
    uses: jpvieirah/central-reusable/.github/workflows/build-reusable.yml@main
    with:
      language: "java"
      environment: "ci"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}