name: CI Java

on:
  push:
    branches: [ "develop", "main" ]
    paths:
      - "java/**"  # Dispara o workflow apenas se houver alterações na pasta "java"
  pull_request:
    branches: [ "develop", "main" ]
    paths:
      - "java/**"  # Dispara o workflow apenas se houver alterações na pasta "java"
  workflow_dispatch:

jobs:
  ci-java:
    uses: ./.github/workflows/build-reusable.yml
    with:
      language: "java"
      environment: "ci"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  call-upload-artifact:
      needs: ci-java  # Garante que o job 'call-upload-artifact' só será executado depois do 'ci-java' finalizar
      uses: ./.github/workflows/upload-artifact-java.yml  # Chama o próximo workflow
      with:
        language: "java"  # Passando o valor do input 'language' para o workflow chamado
        environment: "ci"  # Passando o valor do input 'environment' para o workflow chamado